/******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic sensor
 *
 * Author: Nada Youssef
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

uint16 g_timeHigh = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description: function to initialize the ultrasonic
 * 1- initialize the ICU
 * 2- setup the ICU call back function
 * 3- setup the direction for the trigger pin as output pin
 */
void Ultrasonic_init(void){

	/* structure of type Icu_ConfigType to configure the ICU */
	Icu_ConfigType icu_config = {CLOCK,RISING};
    /*  initialize the ICU */
	Icu_init(&icu_config);
	/* setup the ICU call back function */
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/* setup the direction for the trigger pin as output pin */
	GPIO_setupPinDirection(TRIGGER_PORT, TRIGGER_PIN, PIN_OUTPUT);
	/* write 0 on it as initial value */
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);

}

/*
 * Description:
 * function to Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void){
    /* Set the trigger pin for the required period of time (10 us) */
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_HIGH);
    _delay_us(10);
	GPIO_writePin(TRIGGER_PORT, TRIGGER_PIN, LOGIC_LOW);

}

/*
 * Description:
 * function to Send the trigger pulse by using Ultrasonic_Trigger function.
 * and start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){
	/* send the trigger pulse */
	Ultrasonic_Trigger();
	/* calculate the distance by using the calculated time
	 * distance = speed * time
	 * sound speed = 34000 cm/s
	 * distance = 34000/2 * time
	 * 			= 17000 * time
	 * 			= 17000 x (timer_value) x 1 x 10^-6 cm
	 * 			=(timer_value)/58.8
	 *  */
	return (g_timeHigh/58.8);
}

/*
 * Description: the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void){
	/* static variable to detect how many times the function is called */
	static uint8 g_edgeCount = 0;

	g_edgeCount++;
	if(g_edgeCount == 1)   /* the first rising edge is detected */
	{
		/* Clear the timer counter register to start measurements from the rising edge */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}

	else if(g_edgeCount == 2)    /* the falling edge is detected */
	{
		/* Store the High time value */
        g_timeHigh=Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;

	}

}
